# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'PC_Monitor.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCharts import QChartView
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QSizePolicy, QTabWidget,
    QWidget)

class Ui_PC_Monitor(object):
    def setupUi(self, PC_Monitor):
        if not PC_Monitor.objectName():
            PC_Monitor.setObjectName(u"PC_Monitor")
        PC_Monitor.resize(894, 673)
        icon = QIcon()
        icon.addFile(u"resources/app_icon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        PC_Monitor.setWindowIcon(icon)
        self.PCMonitor = QTabWidget(PC_Monitor)
        self.PCMonitor.setObjectName(u"PCMonitor")
        self.PCMonitor.setGeometry(QRect(10, 40, 861, 581))
        self.cpu = QWidget()
        self.cpu.setObjectName(u"cpu")
        self.cpu_title = QLabel(self.cpu)
        self.cpu_title.setObjectName(u"cpu_title")
        self.cpu_title.setGeometry(QRect(41, 41, 45, 27))
        font = QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.cpu_title.setFont(font)
        self.cpu_name = QLabel(self.cpu)
        self.cpu_name.setObjectName(u"cpu_name")
        self.cpu_name.setGeometry(QRect(600, 40, 219, 16))
        self.cpu_percent_label = QLabel(self.cpu)
        self.cpu_percent_label.setObjectName(u"cpu_percent_label")
        self.cpu_percent_label.setGeometry(QRect(40, 330, 54, 16))
        self.cpu_speed_label = QLabel(self.cpu)
        self.cpu_speed_label.setObjectName(u"cpu_speed_label")
        self.cpu_speed_label.setGeometry(QRect(120, 330, 54, 16))
        self.cpu_basespeed_label = QLabel(self.cpu)
        self.cpu_basespeed_label.setObjectName(u"cpu_basespeed_label")
        self.cpu_basespeed_label.setGeometry(QRect(300, 320, 61, 16))
        self.cpu_slot_label = QLabel(self.cpu)
        self.cpu_slot_label.setObjectName(u"cpu_slot_label")
        self.cpu_slot_label.setGeometry(QRect(300, 350, 54, 16))
        self.cpu_kernel_label = QLabel(self.cpu)
        self.cpu_kernel_label.setObjectName(u"cpu_kernel_label")
        self.cpu_kernel_label.setGeometry(QRect(300, 380, 54, 16))
        self.cpu_logicprocessor_label = QLabel(self.cpu)
        self.cpu_logicprocessor_label.setObjectName(u"cpu_logicprocessor_label")
        self.cpu_logicprocessor_label.setGeometry(QRect(300, 410, 71, 16))
        self.cpu_virtualization_label = QLabel(self.cpu)
        self.cpu_virtualization_label.setObjectName(u"cpu_virtualization_label")
        self.cpu_virtualization_label.setGeometry(QRect(300, 440, 54, 16))
        self.cpu_L1_cache_label = QLabel(self.cpu)
        self.cpu_L1_cache_label.setObjectName(u"cpu_L1_cache_label")
        self.cpu_L1_cache_label.setGeometry(QRect(300, 470, 54, 16))
        self.cpu_L2_cache_label = QLabel(self.cpu)
        self.cpu_L2_cache_label.setObjectName(u"cpu_L2_cache_label")
        self.cpu_L2_cache_label.setGeometry(QRect(300, 490, 54, 16))
        self.cpu_L3_cache_label = QLabel(self.cpu)
        self.cpu_L3_cache_label.setObjectName(u"cpu_L3_cache_label")
        self.cpu_L3_cache_label.setGeometry(QRect(300, 520, 54, 16))
        self.cpu_process_label = QLabel(self.cpu)
        self.cpu_process_label.setObjectName(u"cpu_process_label")
        self.cpu_process_label.setGeometry(QRect(40, 400, 54, 16))
        self.cpu_thread_label = QLabel(self.cpu)
        self.cpu_thread_label.setObjectName(u"cpu_thread_label")
        self.cpu_thread_label.setGeometry(QRect(90, 400, 54, 16))
        self.cpu_handle_label = QLabel(self.cpu)
        self.cpu_handle_label.setObjectName(u"cpu_handle_label")
        self.cpu_handle_label.setGeometry(QRect(160, 400, 54, 16))
        self.cpu_runningtime_label = QLabel(self.cpu)
        self.cpu_runningtime_label.setObjectName(u"cpu_runningtime_label")
        self.cpu_runningtime_label.setGeometry(QRect(40, 460, 81, 16))
        self.graphicsView = QChartView(self.cpu)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(40, 90, 791, 192))
        self.label_2 = QLabel(self.cpu)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(40, 70, 54, 16))
        self.cpu_percent_max = QLabel(self.cpu)
        self.cpu_percent_max.setObjectName(u"cpu_percent_max")
        self.cpu_percent_max.setGeometry(QRect(790, 70, 54, 16))
        self.time_stop = QLabel(self.cpu)
        self.time_stop.setObjectName(u"time_stop")
        self.time_stop.setGeometry(QRect(40, 290, 54, 16))
        self.time_start = QLabel(self.cpu)
        self.time_start.setObjectName(u"time_start")
        self.time_start.setGeometry(QRect(810, 290, 51, 20))
        self.cpu_percent_value = QLabel(self.cpu)
        self.cpu_percent_value.setObjectName(u"cpu_percent_value")
        self.cpu_percent_value.setGeometry(QRect(40, 360, 54, 16))
        self.cpu_speed_value = QLabel(self.cpu)
        self.cpu_speed_value.setObjectName(u"cpu_speed_value")
        self.cpu_speed_value.setGeometry(QRect(120, 360, 54, 16))
        self.cpu_process_value = QLabel(self.cpu)
        self.cpu_process_value.setObjectName(u"cpu_process_value")
        self.cpu_process_value.setGeometry(QRect(40, 420, 31, 16))
        self.cpu_thread_value = QLabel(self.cpu)
        self.cpu_thread_value.setObjectName(u"cpu_thread_value")
        self.cpu_thread_value.setGeometry(QRect(90, 420, 54, 16))
        self.cpu_handle_value = QLabel(self.cpu)
        self.cpu_handle_value.setObjectName(u"cpu_handle_value")
        self.cpu_handle_value.setGeometry(QRect(170, 420, 54, 16))
        self.cpu_runningtime_value = QLabel(self.cpu)
        self.cpu_runningtime_value.setObjectName(u"cpu_runningtime_value")
        self.cpu_runningtime_value.setGeometry(QRect(40, 490, 121, 16))
        self.cpu_basespeed_value = QLabel(self.cpu)
        self.cpu_basespeed_value.setObjectName(u"cpu_basespeed_value")
        self.cpu_basespeed_value.setGeometry(QRect(390, 320, 54, 16))
        self.cpu_slot_value = QLabel(self.cpu)
        self.cpu_slot_value.setObjectName(u"cpu_slot_value")
        self.cpu_slot_value.setGeometry(QRect(390, 350, 54, 16))
        self.cpu_kernel_value = QLabel(self.cpu)
        self.cpu_kernel_value.setObjectName(u"cpu_kernel_value")
        self.cpu_kernel_value.setGeometry(QRect(390, 380, 54, 16))
        self.cpu_logicprocessor_value = QLabel(self.cpu)
        self.cpu_logicprocessor_value.setObjectName(u"cpu_logicprocessor_value")
        self.cpu_logicprocessor_value.setGeometry(QRect(390, 410, 54, 16))
        self.cpu_virtualization_value = QLabel(self.cpu)
        self.cpu_virtualization_value.setObjectName(u"cpu_virtualization_value")
        self.cpu_virtualization_value.setGeometry(QRect(390, 440, 54, 16))
        self.cpu_L1_cache_value = QLabel(self.cpu)
        self.cpu_L1_cache_value.setObjectName(u"cpu_L1_cache_value")
        self.cpu_L1_cache_value.setGeometry(QRect(390, 470, 54, 16))
        self.cpu_L2_cache_value = QLabel(self.cpu)
        self.cpu_L2_cache_value.setObjectName(u"cpu_L2_cache_value")
        self.cpu_L2_cache_value.setGeometry(QRect(390, 490, 54, 16))
        self.cpu_L3_cache_value = QLabel(self.cpu)
        self.cpu_L3_cache_value.setObjectName(u"cpu_L3_cache_value")
        self.cpu_L3_cache_value.setGeometry(QRect(390, 520, 54, 16))
        self.PCMonitor.addTab(self.cpu, "")
        self.memory = QWidget()
        self.memory.setObjectName(u"memory")
        self.PCMonitor.addTab(self.memory, "")
        self.disk = QWidget()
        self.disk.setObjectName(u"disk")
        self.PCMonitor.addTab(self.disk, "")
        self.network = QWidget()
        self.network.setObjectName(u"network")
        self.PCMonitor.addTab(self.network, "")
        self.gpu = QWidget()
        self.gpu.setObjectName(u"gpu")
        self.PCMonitor.addTab(self.gpu, "")

        self.retranslateUi(PC_Monitor)

        self.PCMonitor.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(PC_Monitor)
    # setupUi

    def retranslateUi(self, PC_Monitor):
        PC_Monitor.setWindowTitle(QCoreApplication.translate("PC_Monitor", u"PC_Monitor", None))
        self.cpu_title.setText(QCoreApplication.translate("PC_Monitor", u"CPU", None))
        self.cpu_name.setText(QCoreApplication.translate("PC_Monitor", u"13th Gen Inter(R) Core(TM) i5-13500H", None))
        self.cpu_percent_label.setText(QCoreApplication.translate("PC_Monitor", u"\u5229\u7528\u7387", None))
        self.cpu_speed_label.setText(QCoreApplication.translate("PC_Monitor", u"\u901f\u5ea6", None))
        self.cpu_basespeed_label.setText(QCoreApplication.translate("PC_Monitor", u"\u57fa\u51c6\u901f\u5ea6:", None))
        self.cpu_slot_label.setText(QCoreApplication.translate("PC_Monitor", u"\u63d2\u69fd:", None))
        self.cpu_kernel_label.setText(QCoreApplication.translate("PC_Monitor", u"\u5185\u6838:", None))
        self.cpu_logicprocessor_label.setText(QCoreApplication.translate("PC_Monitor", u"\u903b\u8f91\u5904\u7406\u5668:", None))
        self.cpu_virtualization_label.setText(QCoreApplication.translate("PC_Monitor", u"\u865a\u62df\u5316:", None))
        self.cpu_L1_cache_label.setText(QCoreApplication.translate("PC_Monitor", u"L1\u7f13\u5b58:", None))
        self.cpu_L2_cache_label.setText(QCoreApplication.translate("PC_Monitor", u"L2 \u7f13\u5b58:", None))
        self.cpu_L3_cache_label.setText(QCoreApplication.translate("PC_Monitor", u"L3\u7f13\u5b58:", None))
        self.cpu_process_label.setText(QCoreApplication.translate("PC_Monitor", u"\u8fdb\u7a0b", None))
        self.cpu_thread_label.setText(QCoreApplication.translate("PC_Monitor", u"\u7ebf\u7a0b", None))
        self.cpu_handle_label.setText(QCoreApplication.translate("PC_Monitor", u"\u53e5\u67c4", None))
        self.cpu_runningtime_label.setText(QCoreApplication.translate("PC_Monitor", u"\u6b63\u5e38\u8fd0\u884c\u65f6\u95f4", None))
        self.label_2.setText(QCoreApplication.translate("PC_Monitor", u"% \u5229\u7528\u7387", None))
        self.cpu_percent_max.setText(QCoreApplication.translate("PC_Monitor", u"100%", None))
        self.time_stop.setText(QCoreApplication.translate("PC_Monitor", u"60\u79d2", None))
        self.time_start.setText(QCoreApplication.translate("PC_Monitor", u"0", None))
        self.cpu_percent_value.setText(QCoreApplication.translate("PC_Monitor", u"0", None))
        self.cpu_speed_value.setText(QCoreApplication.translate("PC_Monitor", u"0", None))
        self.cpu_process_value.setText(QCoreApplication.translate("PC_Monitor", u"0", None))
        self.cpu_thread_value.setText(QCoreApplication.translate("PC_Monitor", u"0", None))
        self.cpu_handle_value.setText(QCoreApplication.translate("PC_Monitor", u"0", None))
        self.cpu_runningtime_value.setText(QCoreApplication.translate("PC_Monitor", u"0", None))
        self.cpu_basespeed_value.setText(QCoreApplication.translate("PC_Monitor", u"0", None))
        self.cpu_slot_value.setText(QCoreApplication.translate("PC_Monitor", u"0", None))
        self.cpu_kernel_value.setText(QCoreApplication.translate("PC_Monitor", u"0", None))
        self.cpu_logicprocessor_value.setText(QCoreApplication.translate("PC_Monitor", u"0", None))
        self.cpu_virtualization_value.setText(QCoreApplication.translate("PC_Monitor", u"0", None))
        self.cpu_L1_cache_value.setText(QCoreApplication.translate("PC_Monitor", u"0", None))
        self.cpu_L2_cache_value.setText(QCoreApplication.translate("PC_Monitor", u"0", None))
        self.cpu_L3_cache_value.setText(QCoreApplication.translate("PC_Monitor", u"0", None))
        self.PCMonitor.setTabText(self.PCMonitor.indexOf(self.cpu), QCoreApplication.translate("PC_Monitor", u"CPU", None))
        self.PCMonitor.setTabText(self.PCMonitor.indexOf(self.memory), QCoreApplication.translate("PC_Monitor", u"\u5185\u5b58", None))
        self.PCMonitor.setTabText(self.PCMonitor.indexOf(self.disk), QCoreApplication.translate("PC_Monitor", u"\u78c1\u76d8", None))
        self.PCMonitor.setTabText(self.PCMonitor.indexOf(self.network), QCoreApplication.translate("PC_Monitor", u"\u7f51\u7edc", None))
        self.PCMonitor.setTabText(self.PCMonitor.indexOf(self.gpu), QCoreApplication.translate("PC_Monitor", u"GPU", None))
    # retranslateUi

